sudo: required
services:
  - docker

before_install:
  - docker build -t matthewtfarley/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true matthewtfarley/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-743693824920"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
